name: rise-environment
channels:
  - conda-forge
dependencies:
  - rise
  - fuzzywuzzy
  - python-Levenshtein
  - pandas
  - qgrid
  - bokeh
  - xlrd
  - matplotlib
  - pandas-gbq
  - seaborn
  - chardet
  - pip:
    - sklearn